package gmod.engine_ents;
#if server
/**
	Sends an achievement system related event from the map to the achievement system.
**/
@:forward
abstract Logic_achievement(Entity) to Entity {
    //Inputs
    
    /**
		Enable this entity.
	**/
    public extern inline function FireEnable(delay:Float) {
        untyped this.Fire("Enable",untyped null,delay);
    }
    
    /**
		Disable this entity.
	**/
    public extern inline function FireDisable(delay:Float) {
        untyped this.Fire("Disable",untyped null,delay);
    }
    
    /**
		Removes this entity from the world.
	**/
    public extern inline function FireKill(delay:Float) {
        untyped this.Fire("Kill",untyped null,delay);
    }
    
    /**
		Removes this entity and all its children from the world.
	**/
    public extern inline function FireKillHierarchy(delay:Float) {
        untyped this.Fire("KillHierarchy",untyped null,delay);
    }
    
    /**
		Adds an entity I/O connection to this entity. Format: <output name> <targetname>:<inputname>:<parameter>:<delay>:<max times to fire (-1 == infinite)>. Very dangerous, use with care.
	**/
    public extern inline function FireAddOutput(param:String,delay:Float) {
        untyped this.Fire("AddOutput",untyped param,delay);
    }
    
    /**
		Causes this entity's OnUser1 output to be fired.
	**/
    public extern inline function FireFireUser1(delay:Float) {
        untyped this.Fire("FireUser1",untyped null,delay);
    }
    
    /**
		Causes this entity's OnUser2 output to be fired.
	**/
    public extern inline function FireFireUser2(delay:Float) {
        untyped this.Fire("FireUser2",untyped null,delay);
    }
    
    /**
		Causes this entity's OnUser3 output to be fired.
	**/
    public extern inline function FireFireUser3(delay:Float) {
        untyped this.Fire("FireUser3",untyped null,delay);
    }
    
    /**
		Causes this entity's OnUser4 output to be fired.
	**/
    public extern inline function FireFireUser4(delay:Float) {
        untyped this.Fire("FireUser4",untyped null,delay);
    }
    
    /**
		Toggle the relay between enabled and disabled.
	**/
    public extern inline function FireToggle(delay:Float) {
        untyped this.Fire("Toggle",untyped null,delay);
    }
    
    /**
		Tells the achievement system the specifed event has occured.
	**/
    public extern inline function FireFireEvent(delay:Float) {
        untyped this.Fire("FireEvent",untyped null,delay);
    }
    
    //Keyvalues
    
    /**
		Start Disabled
	**/
    public var StartDisabled(get,set):Logic_achievementStartDisabledChoices;

    @:noCompletion
    public extern inline function get_StartDisabled():Logic_achievementStartDisabledChoices {
        return untyped this.GetKeyValues().StartDisabled;
    }
    
    @:noCompletion
    public extern inline function set_StartDisabled(value:Logic_achievementStartDisabledChoices):Logic_achievementStartDisabledChoices {
        return untyped this.SetKeyValue("StartDisabled",untyped value);
    }
    
    /**
		Name

		The name that other entities refer to this entity by.
	**/
    public var targetname(get,set):String;

    @:noCompletion
    public extern inline function get_targetname():String {
        return untyped this.GetKeyValues().targetname;
    }
    
    @:noCompletion
    public extern inline function set_targetname(value:String):String {
        return untyped this.SetKeyValue("targetname",untyped value);
    }
    
    /**
		Achievement Event

		Named event is sent to the achievement system when this entity receives a 'FireEvent' input.
	**/
    public var AchievementEvent(get,set):Logic_achievementAchievementEventChoices;

    @:noCompletion
    public extern inline function get_AchievementEvent():Logic_achievementAchievementEventChoices {
        return untyped this.GetKeyValues().AchievementEvent;
    }
    
    @:noCompletion
    public extern inline function set_AchievementEvent(value:Logic_achievementAchievementEventChoices):Logic_achievementAchievementEventChoices {
        return untyped this.SetKeyValue("AchievementEvent",untyped value);
    }
    
    //Outputs
    
    /**
		Fired in response to FireUser1 input.
	**/
    public extern inline function OutputOnUser1(callback:Callback<{activator:Logic_achievement}>):CallbackLink {
        return gmod.OutputRunner.addOutput(this,"OnUser1",callback);
    }
    
    /**
		Fired in response to FireUser2 input.
	**/
    public extern inline function OutputOnUser2(callback:Callback<{activator:Logic_achievement}>):CallbackLink {
        return gmod.OutputRunner.addOutput(this,"OnUser2",callback);
    }
    
    /**
		Fired in response to FireUser3 input.
	**/
    public extern inline function OutputOnUser3(callback:Callback<{activator:Logic_achievement}>):CallbackLink {
        return gmod.OutputRunner.addOutput(this,"OnUser3",callback);
    }
    
    /**
		Fired in response to FireUser4 input.
	**/
    public extern inline function OutputOnUser4(callback:Callback<{activator:Logic_achievement}>):CallbackLink {
        return gmod.OutputRunner.addOutput(this,"OnUser4",callback);
    }
    
    /**
		When the event fires, this fires.
	**/
    public extern inline function OutputOnFired(callback:Callback<{activator:Logic_achievement}>):CallbackLink {
        return gmod.OutputRunner.addOutput(this,"OnFired",callback);
    }
    

    
    
    public extern inline function new() {
        this = cast gmod.libs.EntsLib.Create("logic_achievement");
    }
}

enum abstract Logic_achievementStartDisabledChoices(Int) to Int {
	var NO = 0;
	var YES = 1;
}
enum abstract Logic_achievementAchievementEventChoices(String) to String {
	var HL2_HIT_THE_TRASHCAN_COP_WITH_THE_CAN = "ACHIEVEMENT_EVENT_HL2_HIT_CANCOP_WITHCAN";
	var HL2_PUT_THE_CAN_IN_THE_TRASH = "ACHIEVEMENT_EVENT_HL2_PUT_CANINTRASH";
	var HL2_ESCAPE_THE_APARTMENT_BLOCK_RAID = "ACHIEVEMENT_EVENT_HL2_ESCAPE_APARTMENTRAID";
	var HL2_BREAK_THE_MINITELEPORTER_IN_KLEINERS_LAB = "ACHIEVEMENT_EVENT_HL2_BREAK_MINITELEPORTER";
	var HL2_GET_THE_CROWBAR = "ACHIEVEMENT_EVENT_HL2_GET_CROWBAR";
	var HL2_GET_THE_AIRBOAT = "ACHIEVEMENT_EVENT_HL2_GET_AIRBOAT";
	var HL2_GET_THE_AIRBOATS_MOUNTED_GUN = "ACHIEVEMENT_EVENT_HL2_GET_AIRBOATGUN";
	var HL2_DISCOVER_THE_HIDDEN_SINGING_VORTIGAUNT_CAVE_IN_CHAPTER_WATER_HAZARD = "ACHIEVEMENT_EVENT_HL2_FIND_VORTIGAUNTCAVE";
	var HL2_DESTROY_THE_HUNTERCHOPPER_IN_HALFLIFE_2 = "ACHIEVEMENT_EVENT_HL2_KILL_CHOPPER";
	var HL2_FIND_THE_HEV_SUIT_CHARGER_FACEPLATE_IN_ELIS_SCRAPYARD = "ACHIEVEMENT_EVENT_HL2_FIND_HEVFACEPLATE";
	var HL2_GET_THE_GRAVITY_GUN_IN_BLACK_MESA_EAST = "ACHIEVEMENT_EVENT_HL2_GET_GRAVITYGUN";
	var HL2_MAKE_A_BASKET_IN_ELIS_SCRAPYARD = "ACHIEVEMENT_EVENT_HL2_MAKEABASKET";
	var HL2_BEAT_RAVENHOLM_GRAVGUN_ONLY_START = "ACHIEVEMENT_EVENT_HL2_BEAT_RAVENHOLM_NOWEAPONS_START";
	var HL2_BEAT_RAVENHOLM_GRAVGUN_ONLY_END = "ACHIEVEMENT_EVENT_HL2_BEAT_RAVENHOLM_NOWEAPONS_END";
	var HL2_ESCORT_GREGORI_SAFELY_THROUGH_THE_CHURCH_CEMETERY = "ACHIEVEMENT_EVENT_HL2_BEAT_CEMETERY";
	var HL2_KILL_3_ENEMIES_USING_THE_CRANE = "ACHIEVEMENT_EVENT_HL2_KILL_ENEMIES_WITHCRANE";
	var HL2_PIN_THE_SOLDIER_TO_THE_BILLBOARD_WITH_THE_CROSSBOW_IN_CHAPTER_HIGHWAY_17 = "ACHIEVEMENT_EVENT_HL2_PIN_SOLDIER_TOBILLBOARD";
	var HL2_DEFEND_LITTLE_ODESSA_FROM_THE_GUNSHIP_ATTACK = "ACHIEVEMENT_EVENT_HL2_KILL_ODESSAGUNSHIP";
	var HL2_CROSS_THE_ANTLION_BEACH_IN_CHAPTER_SANDTRAPS_WITHOUT_TOUCHING_THE_SAND = "ACHIEVEMENT_EVENT_HL2_BEAT_DONTTOUCHSAND";
	var HL2_GET_INSIDE_NOVA_PROSPEKT = "ACHIEVEMENT_EVENT_HL2_ENTER_NOVAPROSPEKT";
	var HL2_SURVIVE_THE_SECOND_TURRET_STANDOFF_IN_THE_PRISON = "ACHIEVEMENT_EVENT_HL2_BEAT_TURRETSTANDOFF2";
	var HL2_GAIN_COMMAND_OF_A_SQUAD_OF_REBELS_IN_THE_UPRISING = "ACHIEVEMENT_EVENT_HL2_FOLLOWFREEMAN";
	var HL2_GET_THROUGH_THE_TOXIC_TUNNEL_UNDER_CITY_17_IN_HALFLIFE_2 = "ACHIEVEMENT_EVENT_HL2_BEAT_TOXICTUNNEL";
	var HL2_SURVIVE_THE_GENERATOR_PLAZA_STANDOFF_IN_CHAPTER_ANTICITIZEN_ONE = "ACHIEVEMENT_EVENT_HL2_BEAT_PLAZASTANDOFF";
	var HL2_KILL_ALL_OF_THE_SNIPERS_IN_CITY_17 = "ACHIEVEMENT_EVENT_HL2_KILL_ALLC1709SNIPERS";
	var HL2_SHUT_DOWN_THE_SUPRESSION_DEVICE_BY_DISABLING_ITS_GENERATORS = "ACHIEVEMENT_EVENT_HL2_BEAT_SUPRESSIONDEVICE";
	var HL2_SURVIVE_THE_ROOFTOP_STRIDER_BATTLE_IN_THE_RUINS_OF_CITY_17 = "ACHIEVEMENT_EVENT_HL2_BEAT_C1713STRIDERSTANDOFF";
	var HL2_DESTROY_THE_CITADELS_REACTOR_CORE_BEAT_GAME = "ACHIEVEMENT_EVENT_HL2_BEAT_GAME";
	var HL2_GMAN_TRAINSTATION05_ON_KLEINERS_MONITOR = "ACHIEVEMENT_EVENT_HL2_GMAN_KLEINERSLAB";
	var HL2_GMAN_CANALS01_ON_TV_IN_VORT_TRAIN_CAR = "ACHIEVEMENT_EVENT_HL2_GMAN_TRAINCAR";
	var HL2_GMAN_CANALS06_AT_THE_RED_BARN = "ACHIEVEMENT_EVENT_HL2_GMAN_REDBARN";
	var HL2_GMAN_CANALS06_ON_GIANT_OUTDOOR_MONITOR = "ACHIEVEMENT_EVENT_HL2_GMAN_OUTDOORMONITOR";
	var HL2_GMAN_CANALS12_ON_CATWALK = "ACHIEVEMENT_EVENT_HL2_GMAN_CATWALK";
	var HL2_GMAN_CANALS13_TO_THE_LEFT_OF_THE_DAM = "ACHIEVEMENT_EVENT_HL2_GMAN_DAM";
	var HL2_GMAN_TOWN05_AT_THE_END_OF_THE_TRACKS = "ACHIEVEMENT_EVENT_HL2_GMAN_TRAINTRACKS";
	var HL2_GMAN_COAST03_ODESSA_MEETING = "ACHIEVEMENT_EVENT_HL2_GMAN_ODESSA";
	var HL2_GMAN_PRISON02_CONTROL_ROOM_MONITOR = "ACHIEVEMENT_EVENT_HL2_GMAN_PRISONMONITOR";
	var HL2_GMAN_C1702_ON_TV_IN_THE_DESTROYED_FOYER = "ACHIEVEMENT_EVENT_HL2_GMAN_FOYERTV";
	var HL2_LAMDA_SECRET_ENTRANCE_TO_KLEINERS_LAB_IN_TRAINSTATION05 = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_KLEINERSLAB";
	var HL2_LAMDA_CANALS01_BUILDING_BY_TRACKS = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_CANALSSTATION";
	var HL2_LAMDA_CANALS01_VENT_CRAWL = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_VENTCRAWL";
	var HL2_LAMDA_CANALS01A_TUNNEL = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_CANALSTUNNEL";
	var HL2_LAMDA_CANALS02_BELOW_GRATE_IN_SEWER_CORRIDOR = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_SEWERGRATE";
	var HL2_LAMDA_CANALS03_UNDER_STEAM_PIPE = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_STEAMPIPE";
	var HL2_LAMDA_CANALS05_ON_SECOND_LEVEL_OF_CURVED_ROOM = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_CURVEDROOM";
	var HL2_LAMDA_CANALS05_BEFORE_SHANTY_TOWN = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_SHANTYTOWN";
	var HL2_LAMDA_CANALS06_ON_OVERHEAD_METAL_WALKWAY_IN_TUNNEL = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_TUNNELLADDER";
	var HL2_LAMDA_CANALS06_AT_THE_RED_BARN = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_REDBARN";
	var DONT_USE_ME_HL2_LAMDA_CANALS06_OUTSIDE_THE_PIPE_AT_FLOATING_RAMP_PUZZLE = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_FLOATINGRAMP";
	var HL2_LAMDA_CANALS06_OUTSIDE_EXPLODED_TANKER_ZOMBIE_AMBUSH = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_ZOMBIEAMBUSH";
	var HL2_LAMDA_CANALS07_IN_THE_WALL_BELOW_APCS = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_BELOWAPCS";
	var HL2_LAMDA_CANALS08_IN_COUNTERWEIGHTED_BASKET = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_COUNTERWEIGHT";
	var HL2_LAMDA_CANALS08_BEHIND_RAILWAY_BRIDGE_PILING = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_RAILWAYBRIDGE";
	var HL2_LAMDA_CANALS09_ON_WOODEN_PLATFORMS_IN_TUNNEL = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_TUNNELPLATFORMS";
	var HL2_LAMDA_CANALS10_UP_BANKED_SIDE_OF_CANALS_PASSAGE = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_BANKEDCANAL";
	var HL2_LAMDA_CANALS10_IN_WALL_OPENING_AFTER_CANALS_PASSAGE = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_CANALWALL";
	var HL2_LAMDA_CANALS12_RIGHT_SIDE_OF_SPLIT_CHANNEL = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_CHANNELSPLIT";
	var HL2_LAMDA_ELI01_BLACK_MESA_EAST_DOCK = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_BMEDOCK";
	var HL2_LAMDA_TOWN01_THROUGH_DUCTWORK_BEHIND_GENERATORS = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_GENERATORS";
	var HL2_LAMDA_TOWN01_BEHIND_FENCE_IN_CARCRUSHER_ARENA = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_CARCRUSHERARENA";
	var HL2_LAMDA_TOWN01A_IN_ATTIC_OPPOSITE_MAP_EXIT = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_RAVENHOLMATTIC";
	var HL2_LAMDA_TOWN05_TUNNEL_EXIT_FROM_RAVENHOLM_MINE = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_MINETUNNELEXIT";
	var HL2_LAMDA_COAST01_SHACK_AFTER_THE_BUGGY_JUMP = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_COASTSHACK";
	var HL2_LAMDA_COAST03_POISON_HEADCRAB_SHACK = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_POISONSHACK";
	var HL2_LAMDA_COAST04_BROKEN_DOWN_VAN_AFTER_THE_GUNSHIP = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_GUNSHIPVAN";
	var HL2_LAMDA_COAST05_SUICIDE_CITIZENS_GAS_TANK_CACHE = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_SUICIDECITIZEN";
	var HL2_LAMDA_COAST07_FENCED_OFF_AREA_OUTSIDE_OF_TOWN = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_RAILROADSHACK";
	var HL2_LAMDA_COAST09_ABOVE_THE_BATHROOM_IN_THE_BATTERY_PUZZLE_BUILDING = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_COASTABOVEBATTERY";
	var HL2_LAMDA_COAST11_ELEVATED_SHACK_AFTER_THE_BOARD_BRIDGE = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_SANDSHACK";
	var HL2_LAMDA_PRISON02_IN_THE_BOARDED_UP_AREA_OF_THE_GMAN_SIGHTING = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_GMANCACHE";
	var HL2_LAMDA_PRISON03_IN_THE_PRISON_CELL = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_CELLCACHE";
	var HL2_LAMDA_PRISON05_IN_THE_LAUNDRY_UTILITY_ROOM = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_POISONLAUNDRY";
	var HL2_LAMDA_PRISON06_ON_TOP_OF_THE_SODA_MACHINE = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_SODAMACHINE";
	var HL2_LAMDA_C1702_NEXT_TO_FIRST_COMBINE_WALL = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_STREETWARDOGWALL";
	var HL2_LAMBDA_C1704_INSIDE_SHACK_BEFORE_METROCOP_HOLDOUT = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_STREETWARSHACK";
	var HL2_LAMDA_C1705_BEHIND_FENCE_BEFORE_END_OF_MAP = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_STREETWARFENCE";
	var HL2_LAMDA_C1706A_AT_START_OF_FREEWAY_TUNNEL = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_FREEWAYTUNNEL";
	var HL2_LAMDA_C1706B_BEFORE_SECOND_DRAWBRIDGE = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_DRAWBRIDGE";
	var HL2_LAMDA_C1706B_BEHIND_FENCE_BEFORE_END_OF_MAP = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_PLAZAFENCE";
	var HL2_LAMDA_C1708_LOWEST_CATWALK_AT_SEWER_ENTRANCE = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_SEWERSCATWALKS";
	var HL2_LAMDA_C1708_WALL_CUBBY_NEXT_TO_POISON_ZOMBIE = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_POISONZOMBIEALCOVE";
	var HL2_LAMDA_C1708_END_OF_PIPE_HOP_TUNNEL_BY_POISON_ZOMBIE = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_PIPEHOPTUNNEL";
	var HL2_LAMDA_C1708_SIDE_OF_BUILDING_NEXT_TO_HALLWAY_LEADING_TO_LEVEL_EXIT = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_EXITCATWALK";
	var HL2_LAMDA_C1712B_AT_MAP_EXIT = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_ENDOFC1712B";
	var HL2_LAMDA_C1713_WHITE_VAN_IN_UNDERGROUND_GARAGE = "ACHIEVEMENT_EVENT_HL2_LAMDACACHE_WHITEVAN";
	var EP1_REACH_THE_BOTTOM_OF_THE_MAIN_ELEVATOR_SHAFT = "ACHIEVEMENT_EVENT_EP1_BEAT_MAINELEVATOR";
	var EP1_CONTAIN_THE_CITADEL_CORE_START = "ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE_START";
	var EP1_CONTAIN_THE_CITADEL_CORE_END = "ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE_END";
	var EP1_CONTAIN_THE_CITADEL_CORE = "ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE";
	var EP1_CONTAIN_THE_CITADEL_CORE_WITH_NO_STALKER_KILLS = "ACHIEVEMENT_EVENT_EP1_BEAT_CITADELCORE_NOSTALKERKILLS";
	var EP1_SURVIVE_LONG_ENOUGH_TO_GET_ON_THE_ELEVATOR_IN_THE_PARKING_GARAGE = "ACHIEVEMENT_EVENT_EP1_BEAT_GARAGEELEVATORSTANDOFF";
	var EP1_DESTROY_THE_GUNSHIP_IN_THE_HOSPITAL_ATTIC = "ACHIEVEMENT_EVENT_EP1_BEAT_HOSPITALATTICGUNSHIP";
	var EP1_DONT_LET_ANY_CITIZENS_DIE_WHEN_ESCORTING_THEM_TO_THE_ESCAPE_TRAIN_START = "ACHIEVEMENT_EVENT_EP1_BEAT_CITIZENESCORT_NOCITIZENDEATHS_START";
	var EP1_DONT_LET_ANY_CITIZENS_DIE_WHEN_ESCORTING_THEM_TO_THE_ESCAPE_TRAIN_END = "ACHIEVEMENT_EVENT_EP1_BEAT_CITIZENESCORT_NOCITIZENDEATHS_END";
	var EP1_BEAT_EP1_WITHOUT_PICKING_UP_ANY_HEALTH_START = "ACHIEVEMENT_EVENT_EP1_BEAT_GAME_NOHEALTHPICKUPS_START";
	var EP1_BEAT_EP1_WITHOUT_PICKING_UP_ANY_HEALTH_END = "ACHIEVEMENT_EVENT_EP1_BEAT_GAME_NOHEALTHPICKUPS_END";
	var EP1_BEGAN_EP1_FOR_TRACKING_ONE_FREE_BULLET = "ACHIEVEMENT_EVENT_EP1_START_GAME";
	var EP1_BEAT_EP1_FOR_TRACKING_ONE_FREE_BULLET = "ACHIEVEMENT_EVENT_EP1_BEAT_GAME";
	var EP2_HOLD_OFF_THE_ANTLION_INVASION_INSIDE_THE_MINE_SHAFT = "ACHIEVEMENT_EVENT_EP2_BEAT_ANTLIONINVASION";
	var EP2_DEFEAT_BOTH_ANTLION_GUARDS_OUTSIDE_THE_WHITE_FOREST = "ACHIEVEMENT_EVENT_EP2_BEAT_ANTLIONGUARDS";
	var EP2_SURVIVE_THE_HUNTER_AMBUSH_AT_THE_RADIO_TOWER = "ACHIEVEMENT_EVENT_EP2_BEAT_HUNTERAMBUSH";
	var EP2_START_OF_THE_CHOPPER_ARENA_BATTLE = "ACHIEVEMENT_EVENT_EP2_KILL_CHOPPER_NOMISSES_START";
	var EP2_END_OF_THE_CHOPPER_ARENA_BATTLE = "ACHIEVEMENT_EVENT_EP2_KILL_CHOPPER_NOMISSES_END";
	var EP2_DESTROY_THE_COMBINE_CANNON_IN_THE_JUNKYARD = "ACHIEVEMENT_EVENT_EP2_KILL_COMBINECANNON";
	var EP2_BEAT_DOG_IN_THE_RACE_TO_THE_WHITE_FOREST = "ACHIEVEMENT_EVENT_EP2_BEAT_RACEWITHDOG";
	var EP2_UNLOCK_THE_ROCKET_LAUNCHER_LAMBDA_CACHE_IN_CHAPTER_UNDER_THE_RADAR = "ACHIEVEMENT_EVENT_EP2_BEAT_ROCKETCACHEPUZZLE";
	var EP2_SURVIVE_THE_INVASION_AT_WHITE_FOREST_INN = "ACHIEVEMENT_EVENT_EP2_BEAT_WHITEFORESTINN";
	var EP2_SEND_SOME_OBJECT_FROM_CHAPTER_1_INTO_SPACE = "ACHIEVEMENT_EVENT_EP2_PUT_ITEMINROCKET";
	var EP2_SECURE_THE_LAUNCH_DOORS_ON_MISSILE_SILO_2 = "ACHIEVEMENT_EVENT_EP2_BEAT_MISSILESILO2";
	var EP2_SAVE_THE_MISSILE_SILO_FROM_THE_COMBINE_OFFENSIVE = "ACHIEVEMENT_EVENT_EP2_BEAT_GAME";
	var EP2_SAVE_THE_MISSILE_SILO_WITHOUT_LOSING_ANY_BUILDINGS = "ACHIEVEMENT_EVENT_EP2_BEAT_OUTLAND12_NOBUILDINGSDESTROYED";
	var EP2_FOUND_A_RADAR_CACHE_IN_CHAPTER_UNDER_THE_RADAR = "ACHIEVEMENT_EVENT_EP2_FIND_RADAR_CACHE";
	var EP2_RADAR_CACHE_09_FIRST_VAN_CACHE = "ACHIEVEMENT_EVENT_EP2_RADARCACHE_VAN";
	var EP2_RADAR_CACHE_09_RPG_CACHE = "ACHIEVEMENT_EVENT_EP2_RADARCACHE_RPG";
	var EP2_RADAR_CACHE_09_SHACK_FLOOR_BOARD_CACHE = "ACHIEVEMENT_EVENT_EP2_RADARCACHE_SHACK";
	var EP2_RADAR_CACHE_10_CAVE_CACHE = "ACHIEVEMENT_EVENT_EP2_RADARCACHE_CAVE";
	var EP2_RADAR_CACHE_10_HANGING_CRATE_CACHE = "ACHIEVEMENT_EVENT_EP2_RADARCACHE_HANGING";
	var EP2_WEB_CACHE_EP2OUTLAND01A_UNDERWATER_CACHE = "ACHIEVEMENT_EVENT_EP2_WEBCACHE_01";
	var EP2_WEB_CACHE_EP2OUTLAND03_GRIM_PINATA_CACHE = "ACHIEVEMENT_EVENT_EP2_WEBCACHE_02";
	var EP2_WEB_CACHE_EP2OUTLAND03_FIRST_ARENA_EXIT_TUNNEL_WALL_CACHE = "ACHIEVEMENT_EVENT_EP2_WEBCACHE_03";
	var EP2_WEB_CACHE_EP2OUTLAND03_SECOND_ARENA_EXIT_TUNNEL_CEILING_CACHE = "ACHIEVEMENT_EVENT_EP2_WEBCACHE_04";
	var EP2_WEB_CACHE_EP2OUTLAND03_ZOMBINE_GRENADE_TRAP_CACHE = "ACHIEVEMENT_EVENT_EP2_WEBCACHE_05";
	var EP2_WEB_CACHE_EP2OUTLAND04_GEAR_CAVE_ENTRY_WALL_CACHE = "ACHIEVEMENT_EVENT_EP2_WEBCACHE_06";
	var EP2_WEB_CACHE_EP2OUTLAND04_GEAR_CAVE_ROCKFALL_CEILING_CACHE = "ACHIEVEMENT_EVENT_EP2_WEBCACHE_07";
	var EP2_WEB_CACHE_EP2OUTLAND04_GEAR_CAVE_BARNACLE_CEILING_CACHE = "ACHIEVEMENT_EVENT_EP2_WEBCACHE_08";
	var EP2_WEB_CACHE_EP2OUTLAND04_GEAR_CAVE_POISON_CRAB_WALL_CACHE = "ACHIEVEMENT_EVENT_EP2_WEBCACHE_09";
	var PORTAL_ACQUIRE_THE_FULLY_POWERED_APERTURE_SCIENCE_HANDHELD_PORTAL_DEVICE = "ACHIEVEMENT_EVENT_PORTAL_GET_PORTALGUNS";
	var PORTAL_DO_WHATEVER_IT_TAKES_TO_SURVIVE = "ACHIEVEMENT_EVENT_PORTAL_KILL_COMPANIONCUBE";
	var PORTAL_MAKE_THE_CORRECT_PARTY_ESCORT_SUBMISSION_POSITION_DECISION = "ACHIEVEMENT_EVENT_PORTAL_ESCAPE_TESTCHAMBERS";
	var PORTAL_COMPLETE_PORTAL = "ACHIEVEMENT_EVENT_PORTAL_BEAT_GAME";
}




#end
